import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.siteWindow}>
        <div className={styles.body}>
          <div className={styles.sidebar}>
            <input/>
            <Link href="/home">My Profile</Link>
            <Link href="/search">My Friends</Link>
            <Link href="/browse">My Photos</Link>
            <Link href="/share">My Notes</Link>
            <Link href="/invite">My Groups</Link>
            <Link href="/help">My Events</Link>
            <Link href="/logout">My Messages</Link>
            <Link href="/logout">My Account</Link>
            <Link href="/logout">My Privacy</Link>
          </div>

          <div className={styles.horizontalPane}>

            <div className={styles.menu}>
              <div className={styles.fblogo}>facebook</div>
              <div className={styles.menuLinks}>
                <Link href="/home">home</Link>
                <Link href="/search">search</Link>
                <Link href="/browse">browse</Link>
                <Link href="/share">share</Link>
                <Link href="/invite">invite</Link>
                <Link href="/help">help</Link>
                <Link href="/logout">logout</Link>
              </div>
            </div>

            <main className={styles.main}>
              <div className={styles.profileHeader}>
                Matt
                Profile (This is you)
                Facebook
              </div>
              <div className={styles.profileBody}>
                <div className={styles.profileBodySide}>
                  <div>This is a photo of you</div>
                  <Link>View more photos of me</Link>
                  <Link>Read Notes about Me</Link>
                  <Link>Edit My Profile</Link>
                  <Link>Edit My Picture</Link>
                  <Link>Edit My Privacy</Link>
                  <Link>Create a Profile Badge</Link>

                  /* the 'status' pane goes here. not sure what it contains. can't scroll down enough/ */
                  <div>
                  </div>
                </div>
                <div className={styles.profileBodyMain}>
              <details className={styles.miniFeed}>
                <summary>Mini-feed</summary>
                <div className={styles.detailContents}>
                  content that is hidden
                </div>
              </details>

              <details className={styles.personalInfo}>
                <summary>Personal Info <button>Edit</button></summary>
                <div className={styles.detailContents}>
                  <table>
                    <tr>
                      <td>Political Views:</td>
                      <td>Moderate</td>
                    </tr>
                    <tr>
                      <td>Interests:</td>
                      <td>Web Design, Photography, Almost All Music, Tennis, Nintendo DS Lite</td>
                    </tr>

                    <tr>
                      <td>Favorite Music:</td>
                      <td>100 Gecs, xaviersobased, bladee</td>
                    </tr>

                    <tr>
                      <td>Favorite TV Shows:</td>
                      <td>The 100</td>
                    </tr>

                    <tr>
                      <td>Favorite Movies:</td>
                      <td>Tarantino</td>
                    </tr>

                    <tr>
                      <td>Favorite Quotes:</td>
                      <td>"Drama is life with the dull bits cut out." - Alfred Hitchock</td>
                    </tr>
                  </table>
                </div>
              </details>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
