import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Accordion = ({ title, children }) => {
  return (
    <details className={styles.miniFeed}>
      <summary>{title} <button>Edit</button></summary>
      <div className={styles.detailContents}>
        {children}
      </div>
    </details>
  )
}

const InterestTable = ({ interests }) => {
  return (
    <table>
    {interests.map(([name, body]) => {
      return (
        <tr>
          <td>
            {name}:
          </td>
          <td>
            {body.map((component) => (<span>{component}</span>))}
          </td>
        </tr>
      )
    })}
    </table>
  );
}

const profile_interests = [
  ["Email", ["username@example.com"]],
  ["AIM Screenname", ["matthead"]],
  ["Mobile", ["+1 503-555-0199"]],
  ["Sex", ["Male"]],
  ["Interested In", ["Women"]]
];

const personal_interests = [
  ["Political Views", ["Moderate"]],
  ["Interests", ["Web Design", "Photography", "Almost All Music", "Tennis", "Nintendo DS Lite"]],
  ["Favorite Music", ["100 Gecs", "xaviersobased", "Bladee"]],
  ["Favorite TV Shows", ["The 100"]],
  ["Favorite Movies", ["Tarantino"]],
  ["Favorite Quotes", ["\"Drama is life with the dull bits cut out.\" - Alfred Hitchock"]],
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.siteWindowContainer}>
        <div className={styles.siteWindow}>
          <div className={styles.body}>
            <div className={styles.sidebar}>
              <input/>
              <Link href="/home">My Profile</Link>
              <Link href="/search">My Friends</Link>
              <Link href="/browse">My Photos</Link>
              <Link href="/share">My Notes</Link>
              <Link href="/invite">My Groups</Link>
              <Link href="/help">My Events</Link>
              <Link href="/logout">My Messages</Link>
              <Link href="/logout">My Account</Link>
              <Link href="/logout">My Privacy</Link>
            </div>

            <div className={styles.horizontalPane}>
              <div className={styles.menu}>
                <div className={styles.fblogo}>facebook</div>
                <div className={styles.menuLinks}>
                  <Link href="/home">home</Link>
                  <Link href="/search">search</Link>
                  <Link href="/browse">browse</Link>
                  <Link href="/share">share</Link>
                  <Link href="/invite">invite</Link>
                  <Link href="/help">help</Link>
                  <Link href="/logout">logout</Link>
                </div>
              </div>

              <main className={styles.main}>
                <div className={styles.profileHeader}>
                  Matt
                  Profile (This is you)
                  Facebook
                </div>
                <div className={styles.profileBody}>
                  <div className={styles.profileBodySide}>
                    <div>This is a photo of you</div>
                    <div className={styles.profileSideLinks}>
                      <Link href="/photos">View more photos of me</Link>
                      <Link href="/notes">Read Notes about Me</Link>
                      <Link href="/profile">Edit My Profile</Link>
                      <Link href="/pictures">Edit My Picture</Link>
                      <Link href="/privacy">Edit My Privacy</Link>
                      <Link href="/badge">Create a Profile Badge</Link>
                    </div>
                  </div>
                  <div className={styles.profileBodyMain}>
                    <h1>Matt Callum Lastname</h1>
                    <p>Facebook</p>
                    <p>Iowa State Alum</p>
                    <address>Silicon Valley, California</address>
                    <hr/>
                    <InterestTable interests={profile_interests} />

                    <Accordion title="Mini-feed">
                      content that is hidden
                    </Accordion>

                    <Accordion title="Personal Info">
                      <InterestTable interests={personal_interests}/>
                    </Accordion>
                  </div>
                </div>
              </main>
            </div>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
