import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.siteWindow}>
        <div className={styles.body}>
          <div className={styles.sidebar}>
            <input/>
            <Link href="/home">My Profile</Link>
            <Link href="/search">My Friends</Link>
            <Link href="/browse">My Photos</Link>
            <Link href="/share">My Notes</Link>
            <Link href="/invite">My Groups</Link>
            <Link href="/help">My Events</Link>
            <Link href="/logout">My Messages</Link>
            <Link href="/logout">My Account</Link>
            <Link href="/logout">My Privacy</Link>
          </div>
          <div className={styles.horizontalPane}>
            <div className={styles.menu}>
              <div className={styles.fblogo}>facebook</div>
              <div className={styles.menuLinks}>
                <Link href="/home">home</Link>
                <Link href="/search">search</Link>
                <Link href="/browse">browse</Link>
                <Link href="/share">share</Link>
                <Link href="/invite">invite</Link>
                <Link href="/help">help</Link>
                <Link href="/logout">logout</Link>
              </div>
            </div>

            <main className={styles.main}>
              <div></div>
              <details className={styles.miniFeed}>
                <summary>Mini-feed</summary>
                mini feed that's hidden
              </details>

              <details className={styles.personalInfo}>
                <summary>Personal Info <button>Edit</button></summary>
                personal info that's hidden
              </details>
            </main>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
